/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSupplierRouteImport } from './routes/dashboard/supplier'
import { Route as DashboardFarmerRouteImport } from './routes/dashboard/farmer'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSupplierRoute = DashboardSupplierRouteImport.update({
  id: '/dashboard/supplier',
  path: '/dashboard/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFarmerRoute = DashboardFarmerRouteImport.update({
  id: '/dashboard/farmer',
  path: '/dashboard/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/recommendations': typeof RecommendationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/farmer': typeof DashboardFarmerRoute
  '/dashboard/supplier': typeof DashboardSupplierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/recommendations': typeof RecommendationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/farmer': typeof DashboardFarmerRoute
  '/dashboard/supplier': typeof DashboardSupplierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/recommendations': typeof RecommendationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/farmer': typeof DashboardFarmerRoute
  '/dashboard/supplier': typeof DashboardSupplierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/recommendations'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/farmer'
    | '/dashboard/supplier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products'
    | '/recommendations'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/farmer'
    | '/dashboard/supplier'
  id:
    | '__root__'
    | '/'
    | '/products'
    | '/recommendations'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/farmer'
    | '/dashboard/supplier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsRoute: typeof ProductsRoute
  RecommendationsRoute: typeof RecommendationsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  DashboardFarmerRoute: typeof DashboardFarmerRoute
  DashboardSupplierRoute: typeof DashboardSupplierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/supplier': {
      id: '/dashboard/supplier'
      path: '/dashboard/supplier'
      fullPath: '/dashboard/supplier'
      preLoaderRoute: typeof DashboardSupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/farmer': {
      id: '/dashboard/farmer'
      path: '/dashboard/farmer'
      fullPath: '/dashboard/farmer'
      preLoaderRoute: typeof DashboardFarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsRoute: ProductsRoute,
  RecommendationsRoute: RecommendationsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  DashboardFarmerRoute: DashboardFarmerRoute,
  DashboardSupplierRoute: DashboardSupplierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
